blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/rudizl/platinum-weather-card-plus-charts/discussions
    about: For general questions, use Discussions instead of Issues
