resources:
  - url: http://127.0.0.1:5000/platinum-weather-card.js
    type: module
views:
  - title: Dev
    cards:
      - type: custom:platinum-weather-card-plus-charts
        weather_entity: weather.demo
        forecast_type: daily
        test_gui: true
